# 指定语言环境
language: node_js

# node版本
node_js: stable

# 设置只监听哪个分支
branches:
  only:
  - source

# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  directories:
    - node_modules

before_install:
  - git config user.name "Veg_chic"
  - git config user.email "h_foryou@163.com"
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  # 替换同目录下的 _config.yml 文件中 gh_token 字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/REPO_TOKEN/${REPO_TOKEN}/g" ./_config.yml
  - hexo deploy

# End: Build LifeCycle
