# 指定语言环境
language: node_js

# node版本
node_js: 
  - 10.12.0

# 设置只监听哪个分支
branches:
  only:
  - source

# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  directories:
    - node_modules

before_install:
  - git config user.name "Veg_chic"
  - git config user.email "h_foryou@163.com"
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

after_script:
  # 替换同目录下的 _config.yml 文件中 REPO_TOKEN 字符串
  - sed -i "s/REPO_TOKEN/${REPO_TOKEN}/g" ./_config.yml
  - sed -i "s/CLIENT_ID/${CLIENT_ID}/g" ./_config.yml
  - sed -i "s/CLIENT_SECRET/${CLIENT_SECRET}/g" ./_config.yml
  - hexo deploy

# End: Build LifeCycle
